import blogSingleLargeImage1 from '@assets/images/blog_single_large1.png'
import blogSingleLargeImage2 from '@assets/images/blog_single_large2.png'
import blogSingleLargeImage3 from '@assets/images/blog_single_large3.png'
import blogSingleLargeImageG from '@assets/images/blog_single_largeG.png'
import blogSingleLargeImageK from '@assets/images/blog_single_largeK.png'
import blogSingleLargeImageW from '@assets/images/blog_single_largeW.png'
import blogSingleImage1 from '@assets/images/blog_single1.png'
import blogSingleImage2 from '@assets/images/blog_single2.png'
import blogSingleImage3 from '@assets/images/blog_single3.png'
import blogSingleImage4 from '@assets/images/blog_single4.png'
import { IBlogPost } from '@interfaces/index'
import { BLOG_BASE_ROUTE } from './router'

const commonPreviewText = `Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...`
const commonText = `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Nulla rhoncus consectetur eros non iaculis “Vivamus lectus enim, convallis nec dapibus vel, semper id ante. Morbi pulvinar sapien nulla, eu dignissim enim ullamcorper vitae”.
Ut sit amet neque vel mauris consequat aliquam at in arcu. Ut vulputate, augue luctus dignissim pretium, elit magna placerat elit, at venenatis lacus arcu eget quam. Fusce nec cursus mi, sed blandit.
Phasellus tristique eu nisl eu consectetur. Morbi urna massa, imperdiet in mauris et, euismod vestibulum lacus. Integer enim elit, tincidunt aliq uam ligula id, lacinia auctor orci. Sed quis lobortis eros. Fusce id commodo libero. Praesent mollis velit ac accumsan ultrices. Ut convallis ipsum pulvinar ante maximus suscipit.
Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, eu euismod augue bibendum. In volutpat libero velit, et mattis tortor placerat eget.
Ut nec aliquam urna, et varius massa. Praesent eu nisl ac ex maximus iaculis. Sed placerat, ligula vel tempor pellentesque, odio ipsum lobortis orci, sit amet fermentum ex nunc ac diam.`

export const BLOG_PAGE_POSTS: IBlogPost[] = [
	{
		id: 'blog-1',
		title: '2022 software development trends explained with benefits',
		previewText: commonPreviewText,
		text: commonText,
		date: '22 June 2022',
		image: blogSingleLargeImage1,
		imagePreview: blogSingleImage1,
		author: 'William Pond',
		category: 'Software development',
		tags: ['Data', 'Future', 'Information security'],
		viewsCount: 125,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-2',
		title: 'ISO 13485 compliance of medical devices',
		previewText: commonPreviewText,
		text: commonText,
		date: '23 June 2022',
		image: blogSingleLargeImageK,
		imagePreview: blogSingleLargeImageK,
		author: 'Kazimir Zalubenko',
		category: 'Information security',
		tags: ['Management', 'Information security', 'CMR'],
		viewsCount: 4890,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-3',
		title: 'Business analysis helps you  in finance',
		previewText: commonPreviewText,
		text: commonText,
		date: '24 June 2022',
		image: blogSingleLargeImageK,
		imagePreview: blogSingleImage3,
		author: 'Kazimir Zalubenko',
		category: 'Internet of things',
		tags: ['Proxy', 'CMR'],
		viewsCount: 135,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-4',
		title: 'Benefits of telemedicine in nursing homes',
		previewText: commonPreviewText,
		text: commonText,
		date: '25 June 2022',
		image: blogSingleLargeImageG,
		imagePreview: blogSingleLargeImageG,
		author: 'Gustavo Fring',
		category: 'Digital transformation',
		tags: ['App', 'Media'],
		viewsCount: 985,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-5',
		title: '5 web portal examples your business can learn from',
		previewText: commonPreviewText,
		text: commonText,
		date: '26 June 2022',
		image: blogSingleLargeImageW,
		imagePreview: blogSingleLargeImageW,
		author: 'Walter Hartwell White',
		category: 'Healthcare it',
		tags: ['App', 'Big data', 'CMR', 'Media'],
		viewsCount: 1175,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-6',
		title: '2022 software development trends explained with benefits',
		previewText: commonPreviewText,
		text: commonText,
		date: '27 June 2022',
		image: blogSingleLargeImageW,
		imagePreview: blogSingleImage3,
		author: 'Walter Hartwell White',
		category: 'Healthcare it',
		tags: ['CIO', 'Team', 'Media'],
		viewsCount: 1365,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-7',
		title: 'ISO 13485 compliance of medical devices',
		previewText: commonPreviewText,
		text: commonText,
		date: '28 June 2022',
		image: blogSingleLargeImageK,
		imagePreview: blogSingleImage2,
		author: 'Kazimir Zalubenko',
		category: 'Information security',
		tags: ['Future', 'Media'],
		viewsCount: 5980,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-8',
		title: 'Business analysis helps you  in finance',
		previewText: commonPreviewText,
		text: commonText,
		date: '24 June 2022',
		image: blogSingleLargeImageK,
		imagePreview: blogSingleLargeImageK,
		author: 'Kazimir Zalubenko',
		category: 'Digital transformation',
		tags: ['Startup', 'Data', 'Media'],
		viewsCount: 78,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-9',
		title: 'Benefits of telemedicine in nursing homes',
		previewText: commonPreviewText,
		text: commonText,
		date: '25 June 2022',
		image: blogSingleLargeImageG,
		imagePreview: blogSingleImage4,
		author: 'Gustavo Fring',
		category: 'Digital transformation',
		tags: ['CIO', 'Data analytics'],
		viewsCount: 784,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-10',
		title: '5 web portal examples your business can learn from',
		previewText: commonPreviewText,
		text: commonText,
		date: '29 June 2022',
		image: blogSingleLargeImageW,
		imagePreview: blogSingleLargeImageW,
		author: 'Walter Hartwell White',
		category: 'Healthcare it',
		tags: ['App', 'Big data'],
		viewsCount: 7815,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-11',
		title: '2022 software development trends explained with benefits',
		previewText: commonPreviewText,
		text: commonText,
		date: '31 June 2022',
		image: blogSingleLargeImage1,
		imagePreview: blogSingleImage1,
		author: 'William Pond',
		category: 'Software development',
		tags: ['Data', 'Future'],
		viewsCount: 135,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-12',
		title: 'ISO 13485 compliance of medical devices',
		previewText: commonPreviewText,
		text: commonText,
		date: '30 June 2022',
		image: blogSingleLargeImage2,
		imagePreview: blogSingleImage2,
		author: 'Kazimir Zalubenko',
		category: 'Information security',
		tags: ['Management', 'Information security'],
		viewsCount: 1484,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-13',
		title: 'Business analysis helps you  in finance',
		previewText: commonPreviewText,
		text: commonText,
		date: '28 June 2022',
		image: blogSingleLargeImage3,
		imagePreview: blogSingleImage3,
		author: 'Kazimir Zalubenko',
		category: 'Internet of things',
		tags: ['App', 'App'],
		viewsCount: 889,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-14',
		title: 'Benefits of telemedicine in nursing homes',
		previewText: commonPreviewText,
		text: commonText,
		date: '25 June 2022',
		image: blogSingleLargeImageG,
		imagePreview: blogSingleImage4,
		author: 'Gustavo Fring',
		category: 'Digital transformation',
		tags: ['App', 'Media'],
		viewsCount: 9568,
		baseRoute: BLOG_BASE_ROUTE,
	},
	{
		id: 'blog-15',
		title: '5 web portal examples your business can learn from',
		previewText: commonPreviewText,
		text: commonText,
		date: '26 June 2022',
		image: blogSingleLargeImageW,
		imagePreview: blogSingleLargeImageW,
		author: 'Walter Hartwell White',
		category: 'Healthcare it',
		tags: ['CMR', 'Proxy'],
		viewsCount: 12053,
		baseRoute: BLOG_BASE_ROUTE,
	},
]
