export const ABOUT_US_ROUTE = '/about-us-page'
export const BLOG_ROUTE = '/blog-page'
export const CONTACTS_ROUTE = '/contacts-page'
export const FAQS_ROUTE = '/faqs-page'
export const HOME_PAGE_ROUTE = '/'
export const OUR_TEAM_ROUTE = '/out-team-page'
export const SERVICES_ROUTE = '/services-page'
export const SOLUTIONS_ROUTE = '/solutions-page'
